# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(240, 320)
        Form.setMinimumSize(QtCore.QSize(240, 320))
        Form.setMaximumSize(QtCore.QSize(240, 320))
        self.groupBox_Input = QtWidgets.QGroupBox(Form)
        self.groupBox_Input.setGeometry(QtCore.QRect(10, 10, 221, 121))
        self.groupBox_Input.setObjectName("groupBox_Input")
        self.textEdit_Document = QtWidgets.QTextEdit(self.groupBox_Input)
        self.textEdit_Document.setGeometry(QtCore.QRect(70, 20, 141, 91))
        self.textEdit_Document.setObjectName("textEdit_Document")
        self.widget = QtWidgets.QWidget(self.groupBox_Input)
        self.widget.setGeometry(QtCore.QRect(11, 21, 51, 91))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Document = QtWidgets.QLabel(self.widget)
        self.label_Document.setObjectName("label_Document")
        self.gridLayout.addWidget(self.label_Document, 0, 0, 1, 1)
        self.pushButton_Select = QtWidgets.QPushButton(self.widget)
        self.pushButton_Select.setObjectName("pushButton_Select")
        self.gridLayout.addWidget(self.pushButton_Select, 1, 0, 1, 1)
        self.pushButton_Confirm = QtWidgets.QPushButton(self.widget)
        self.pushButton_Confirm.setObjectName("pushButton_Confirm")
        self.gridLayout.addWidget(self.pushButton_Confirm, 2, 0, 1, 1)
        self.groupBox_Output = QtWidgets.QGroupBox(Form)
        self.groupBox_Output.setGeometry(QtCore.QRect(10, 140, 221, 161))
        self.groupBox_Output.setObjectName("groupBox_Output")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_Output)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 20, 201, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Name = QtWidgets.QLabel(self.layoutWidget)
        self.label_Name.setObjectName("label_Name")
        self.gridLayout_2.addWidget(self.label_Name, 0, 0, 1, 1)
        self.lineEdit_Name = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.gridLayout_2.addWidget(self.lineEdit_Name, 0, 1, 1, 1)
        self.label_Process = QtWidgets.QLabel(self.layoutWidget)
        self.label_Process.setObjectName("label_Process")
        self.gridLayout_2.addWidget(self.label_Process, 1, 0, 1, 1)
        self.progressBar_Process = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar_Process.setProperty("value", 24)
        self.progressBar_Process.setObjectName("progressBar_Process")
        self.gridLayout_2.addWidget(self.progressBar_Process, 1, 1, 1, 1)
        self.label_Statement = QtWidgets.QLabel(self.layoutWidget)
        self.label_Statement.setObjectName("label_Statement")
        self.gridLayout_2.addWidget(self.label_Statement, 2, 0, 1, 1)
        self.lineEdit_Statement = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_Statement.setObjectName("lineEdit_Statement")
        self.gridLayout_2.addWidget(self.lineEdit_Statement, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PDF合并器"))
        self.groupBox_Input.setTitle(_translate("Form", "选择区"))
        self.label_Document.setText(_translate("Form", "文件选择"))
        self.pushButton_Select.setText(_translate("Form", "选择"))
        self.pushButton_Confirm.setText(_translate("Form", "合并"))
        self.groupBox_Output.setTitle(_translate("Form", "输出区"))
        self.label_Name.setText(_translate("Form", "文件名称"))
        self.label_Process.setText(_translate("Form", "进度"))
        self.label_Statement.setText(_translate("Form", "合并状态"))
